controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



send_mailjet_email:
    path: /send-mailjet-email
    controller: App\Controller\EmailController::sendMailjetEmail


